### ISSUE TITLE
Add a fromObject method to JsonRequest/JsonResponseAssertion

### ISSUE THREAD

**Issue by KPull** [bastion-dev/Bastion#21]
We need to add a factory method, `fromObject()` or `fromModel()`, which takes any Java object instance, serializes it using a JSON serializer (eg. Jackson) and use the serialized object as the request body or expected body (for assertions).

**Comment by KPull** [comment]
Interested in this @borgmatthew? 😄

**Comment by borgmatthew** [comment]
Yes, I'm interested in this. I'll work on it.

**Comment by KPull** [comment]
Fixed in #75.
