### ISSUE TITLE
Update the methods related to HTTP 'body' to refer to 'entity' instead

### ISSUE THREAD

**Issue by KPull** [bastion-dev/Bastion#29]
We incorrectly refer to the content data inside HTTP message as the content 'body'. The HTTP specification calls this the "HTTP Entity". Even though this is a breaking API change, I believe that, given the library is still in BETA, we change all references to "body" and update them to "entity" instead to better reflect the standard.

**Comment by KPull** [comment]
Since the library is being used by people already, I think we leave it as is now since it's not a big deal anyway.

**Comment by maria-camenzuli** [comment]
I think the entity in the Http spec is not just the body. It is the body + certain headers.

"An entity consists of entity-header fields and an entity-body".

So I think we're using body correctly, since the headers are unrelated.

**Comment by KPull** [comment]
As explained in http://stackoverflow.com/questions/9197745/what-exactly-is-an-http-entity, `Body` is indeed the correct terminology. That's nice! :)

I'm closing the issue.
