### ISSUE TITLE
Groovy tests fail while running in IDE

### ISSUE THREAD

**Issue by benjie332** [bastion-dev/Bastion#49]
When running all tests in IntelliJ, the groovy test seems to fail with a NPE.

**Comment by KPull** [comment]
I knew about this but thought it was just my IDE's configuration. It would be good to know if other IDE's (Netbeans or Eclipse) behave similarly.

**Comment by KPull** [comment]
The `BastionRunner` has been removed so this should no longer occur. Thanks for the report.
