### ISSUE TITLE
`BastionRunner` not using `BastionBuilderImpl#getDescriptiveText`

### ISSUE THREAD

**Issue by ericathedev** [bastion-dev/Bastion#50]
The name associated with the `HttpRequest` is meant to describe the request type (eg. 'Register a User'). The descriptive text with the Bastion test builder is meant to add additional info about the specific test (eg. 'Invalid Registration').

These two should appear in test reports in `BastionRunner` using the method `BastionBuilderImpl#getDescriptiveText`, however this is not currently being used inside the Bastion test builder.

As discussed in KPull/Bastion#34.

**Comment by FrelliBB** [comment]
@KPull I think we can close this with the removal of `BastionRunner`.

**Comment by KPull** [comment]
Yep. I'm closing this issue since the `BastionRunner` has been removed.
