### ISSUE TITLE
Separate the Bastion repository into its own account/organisation

### ISSUE THREAD

**Issue by KPull** [bastion-dev/Bastion#51]
At the moment, the Bastion repository is under the `KPull` account. In the spirit of open-source and, as an effort for building a community that actively contributes to Bastion, I believe we should split the Bastion repository under its own Bastion organisation, separate from the `KPull` account.

The main Bastion repository will always have the latest Bastion version as its `master` branch. I would then make pull requests to the main repository as everyone else, from my own account.

Does anyone have any better suggestions for managing this?

**Comment by FrelliBB** [comment]
I think this should be a priority because once this is done we would have to migrate all the issues as well.

**Comment by KPull** [comment]
On https://help.github.com/articles/about-repository-transfers/ it says that everything should move automatically so we shouldn't have any problems with it. I'll try to do this, next in line. :)

**Comment by KPull** [comment]
By the way, we need a username for the organisation which goes into the URL for the repository. Now `Bastion` has already been taken. We need another username. We can do `bastion-rocks`, `bastion-group`, `bastion-library`, `bastion-framework`, `bastion-lib`, etc.

I like `bastion-org`, I think. Any other ideas?

**Comment by KPull** [comment]
I did this. You can see the Bastion organisation page here: https://github.com/bastion-dev
