### ISSUE TITLE
Make JsonSchemaAssertions check for JSON content-type

### ISSUE THREAD

**Issue by KPull** [bastion-dev/Bastion#59]
The `JsonSchemaAssertions` object does not assert for `application/json` in the content-type header. It should behave similar to `JsonResponseAssertion` in that it checks that the content-type is `application/json`. It should also allow the user to override the expected content-type using `overrideContentType()`.

**Comment by KPull** [comment]
@maria-camenzuli, want to take a look at this? :)

**Comment by maria-camenzuli** [comment]
Yes, I will.

**Comment by KPull** [comment]
Fixed in #65.
