### ISSUE TITLE
FileRequest cannot guess given file's MIME type on MacOS

### ISSUE THREAD

**Issue by maria-camenzuli** [bastion-dev/Bastion#63]
The test `contentType_jsonFileType_contentTypeShouldBeJson` is failing when building Bastion on Mac. Bastion is failing to detect the file type and is therefore resorting to the default `text/plain` filetype instead of the expected `application/json`.

I have discussed this with @KPull who found the following related links:
- http://stackoverflow.com/questions/12407479/why-does-files-probecontenttype-return-null
- http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7133484

**Comment by KPull** [comment]
Yes, thanks for bringing this to our attention. So I think for this, we can put this down as a _Known Issue_ and skip the test in case it is running on a Mac. We can use JUnit's `Assume` class for this: http://junit.sourceforge.net/javadoc/org/junit/Assume.html. We should also make a note of this in `FileRequest`'s JavaDoc.

Want to do it yourself or shall I do it, @maria-camenzuli?

**Comment by FrelliBB** [comment]
This might be resolved with https://github.com/bastion-dev/Bastion/pull/89

**Comment by FrelliBB** [comment]
@maria-camenzuli could you check again if the test still fails on MacOS? I think this should be resolved now.

**Comment by maria-camenzuli** [comment]
Built `develop` on MacOS successfully.

**Comment by FrelliBB** [comment]
Wonderful, thanks :)
